namespace :gettext do
  desc 'Writes all states to a locale file so that gettext:find can find them'
  task write_states: :environment do
    File.open File.join(Rails.root, 'locale', 'state_translations.rb'), 'w' do |file|
      file.puts '# Generated by rake gettext:write_states'
      file.puts
      State.all.each {|state| file.puts %Q(N_(#{state.name.inspect})) }
    end
  end
end
